version: '3.7'

services:
  mysql:
    container_name: docker_mysql
    image: mysql:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports: 
      - 3306:3306
    networks: 
      - internal

  symfony_nginx:
    container_name: docker_nginx
    build: 
      context: ./docker/back/
      args: 
        BACKEND_URL: ${BACKEND_URL}
        WORKDIR_BACK: ${WORKDIR_BACK}
        PHP_FPM_USER: ${PHP_FPM_USER}
        PHP_FPM_GROUP: ${PHP_FPM_GROUP}
        PHP_FPM_LISTEN_MODE: ${PHP_FPM_LISTEN_MODE}
        PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
        PHP_MAX_UPLOAD: ${PHP_MAX_UPLOAD}
        PHP_MAX_FILE_UPLOAD: ${PHP_MAX_FILE_UPLOAD}
        PHP_MAX_POST: ${PHP_MAX_POST}
        PHP_DISPLAY_ERRORS: ${PHP_DISPLAY_ERRORS}
        PHP_DISPLAY_STARTUP_ERRORS: ${PHP_DISPLAY_STARTUP_ERRORS}
        PHP_ERROR_REPORTING: ${PHP_ERROR_REPORTING}
        PHP_CGI_FIX_PATHINFO: ${PHP_CGI_FIX_PATHINFO}
        TIMEZONE: ${TIMEZONE}
    env_file: .env
    volumes: 
      - ./${DIRECTORY_BACK}:${WORKDIR_FRONT}
    ports: 
      - 80:80
    networks: 
      - internal

  react:
    container_name: docker_react
    build:
      context: ./docker/front/
      args: 
        WORKDIR_FRONT: ${WORKDIR_FRONT}
    env_file: .env
    volumes: 
      - ./${DIRECTORY_FRONT}:${WORKDIR_FRONT}
    ports: 
      - 3000:3000
    networks: 
      - internal

networks: 
  internal: