version: '3.7'

services:
  mysql:
    container_name: docker_mysql
    image: mysql:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks: 
      - internal

  symfony_nginx:
    container_name: docker_nginx
    build: 
      context: ./docker/back/
      args: 
        USERNAME: ${USERNAME}
        PHP_FPM_USER: ${PHP_FPM_USER}
        PHP_FPM_GROUP: ${PHP_FPM_GROUP}
        PHP_FPM_LISTEN_MODE: ${PHP_FPM_LISTEN_MODE}
        PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
        PHP_MAX_UPLOAD: ${PHP_MAX_UPLOAD}
        PHP_MAX_FILE_UPLOAD: ${PHP_MAX_FILE_UPLOAD}
        PHP_MAX_POST: ${PHP_MAX_POST}
        PHP_DISPLAY_ERRORS: ${PHP_DISPLAY_ERRORS}
        PHP_DISPLAY_STARTUP_ERRORS: ${PHP_DISPLAY_STARTUP_ERRORS}
        PHP_ERROR_REPORTING: ${PHP_ERROR_REPORTING}
        PHP_CGI_FIX_PATHINFO: ${PHP_CGI_FIX_PATHINFO}
        TIMEZONE: ${TIMEZONE}
    env_file: .env
    volumes: 
      - ./back:/var/www/back
    ports: 
      - 80:80
    networks: 
      - internal

  react:
    container_name: docker_react
    image: node:lts
    volumes: 
      - ./front:/var/www/front
    networks: 
      - internal

networks: 
  internal: